### ISSUE TITLE
Python path issue: blur function overwrites python module path for blur.transforms.

### ISSUE THREAD

**Issue by mgrinshpon** [albumentations-team/albumentations#2498]
## Describe the bug

It is not possible to write out the following code and have it work as of albumentations 2.0.3 or newer on Python 3.12:
```python
import albumentations.augmentations.blur.transforms

albumentations.augmentations.blur.transforms.MotionBlur()
```

### Expected behavior

I can run the following line of code:
```python
from albumentations.augmentations.blur.transforms import MotionBlur
```

### Additional context

This breaks instantiation via path from https://github.com/facebookresearch/hydra and https://github.com/mit-ll-responsible-ai/hydra-zen 

As an example, the following code fails as a result:
```python
import albumentations as A
from hydra_zen import builds, instantiate

instantiate(builds(A.MotionBlur))
```
This is because `builds` attempts to create the following omegaconf:
```yaml
    - _target_: albumentations.augmentations.blur.transforms.MotionBlur
      blur_limit:
      - 3
      - 7
      allow_shifted: false
      angle_range:
      - 165
      - 195
      direction_range:
      - -1
      - 1
      p: 0.5
```
However, because blur is in the python path as a function from augmentations importing the _function_ blur, the _module_ blur.transforms ceases to exist. This happens due to the `from x import *` lines in most of these python files.
