### ISSUE TITLE
Serialization of albumentations.pytorch.transforms classes

### ISSUE THREAD

**Issue by Andredance** [albumentations-team/albumentations#613]
## 🐛 Bug

I use augmentations from the config and deserialize them using the from_dict method. I ran into the problem that if you try to deserialize the __ToTensor__ or __ToTensorV2__ methods from the __albumentations.pytorch.transform__ package, it will not work until I do the unnecessary import 'from albumentations.pytorch.transforms import ToTensor/ToTensorV2' with my hands in the code. 

This way the code will look(if we have ToTensorV2 or ToTensor inside config)
```
from albumentations.pytorch.transforms import ToTensorV2
from albumentations.core.serialization import from_dict

transforms = from_dict(config["augmentations"])
```
instead of
```
from albumentations.core.serialization import from_dict

transforms = from_dict(config["augmentations"])
```

## To Reproduce

1. Create augmentation config:
```
aug:
      transform:
        __class_fullname__: albumentations.core.composition.Compose
        transforms:
          - __class_fullname__: albumentations.augmentations.transforms.LongestMaxSize
            max_size: 224
          - __class_fullname__: albumentations.augmentations.transforms.PadIfNeeded
            min_height: 224
            min_width: 224
            border_mode: 0
          - __class_fullname__: albumentations.augmentations.transforms.HorizontalFlip
            p: 0.5
          - __class_fullname__: albumentations.augmentations.transforms.Normalize
          - __class_fullname__: albumentations.pytorch.transforms.ToTensorV2
```
2. Try to run this peace of code(config loaded from file)
```
from albumentations.core.serialization import from_dict

transforms = from_dict(config["augmentations"])
```
3. We receive __KeyError: 'albumentations.pytorch.transforms.ToTensorV2'__
```
  File "/home/user/projects/diplom/data/transforms.py", line 6, in get_transforms
    transforms = from_dict(config["aug"])
  File "/home/user/anaconda3/envs/diplom/lib/python3.7/site-packages/albumentations/core/serialization.py", line 101, in from_dict
    from_dict({"transform": t}, lambda_transforms=lambda_transforms) for t in args["transforms"]
  File "/home/user/anaconda3/envs/diplom/lib/python3.7/site-packages/albumentations/core/serialization.py", line 101, in <listcomp>
    from_dict({"transform": t}, lambda_transforms=lambda_transforms) for t in args["transforms"]
  File "/home/user/anaconda3/envs/diplom/lib/python3.7/site-packages/albumentations/core/serialization.py", line 98, in from_dict
    cls = SERIALIZABLE_REGISTRY[name]
KeyError: 'albumentations.pytorch.transforms.ToTensorV2'
```
## Expected behavior
I think that there should be possibility to deserialize all features of albumentations(ToTensor and ToTensorV2 too). Because it works fine with augmentations and user may not know that he must do the import of a separate package with his hands so that deserialization works.

## Environment

 - Albumentations version (e.g., 0.1.8): 0.4.5
 - Python version (e.g., 3.7): 3.7.7
 - OS (e.g., Linux): Ubuntu 18.04.3 LTS (Bionic Beaver)
 - How you installed albumentations (`conda`, `pip`, source): pip

## Additional context 
If this is still the expected behavior, I would like to see it in the documentation. 
Maybe this is poorly reflected in the documentation or I missed it at all
